version: 2.1

orbs:
  architect: giantswarm/architect@4.33.0

workflows:
  build:
    jobs:
      - architect/go-build:
          name: go-build
          binary: object-storage-operator
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-docker:
          context: "architect"
          name: push-to-docker
          image: "docker.io/giantswarm/object-storage-operator"
          username_envar: "DOCKER_USERNAME"
          password_envar: "DOCKER_PASSWORD"
          requires:
            - go-build
          # Needed to trigger job also on git tag.
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-docker:
          context: "architect"
          name: push-to-quay
          image: "quay.io/giantswarm/object-storage-operator"
          username_envar: "QUAY_USERNAME"
          password_envar: "QUAY_PASSWORD"
          requires:
            - go-build
          # Needed to trigger job also on git tag.
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-docker:
          context: "architect"
          name: push-to-aliyun
          image: "giantswarm-registry.cn-shanghai.cr.aliyuncs.com/giantswarm/object-storage-operator"
          username_envar: "ALIYUN_USERNAME"
          password_envar: "ALIYUN_PASSWORD"
          requires:
            - go-build
          # Needed to trigger job also on git tag.
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-app-catalog:
          context: "architect"
          executor: "app-build-suite"
          name: push-to-app-catalog
          app_catalog: "control-plane-catalog"
          app_catalog_test: "control-plane-test-catalog"
          chart: "object-storage-operator"
          requires:
            - push-to-docker
            - push-to-quay
          # Needed to trigger job also on git tag.
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          context: "architect"
          name: capa-app-collection
          app_name: "object-storage-operator"
          app_namespace: "object-storage-operator"
          app_collection_repo: "capa-app-collection"
          requires:
            - push-to-app-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          context: "architect"
          name: capz-app-collection
          app_name: "object-storage-operator"
          app_namespace: "object-storage-operator"
          app_collection_repo: "capz-app-collection"
          requires:
            - push-to-app-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
