# permissions for end users to view buckets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: bucket-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: object-storage-operator
    app.kubernetes.io/part-of: object-storage-operator
    app.kubernetes.io/managed-by: kustomize
  name: bucket-viewer-role
rules:
- apiGroups:
  - objectstorage.giantswarm.io
  resources:
  - buckets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - objectstorage.giantswarm.io
  resources:
  - buckets/status
  verbs:
  - get
