apiVersion: objectstorage.giantswarm.io/v1alpha1
kind: Bucket
metadata:
  labels:
    app.kubernetes.io/name: bucket
    app.kubernetes.io/instance: bucket-sample
    app.kubernetes.io/part-of: object-storage-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: object-storage-operator
  name: bucket-sample
spec:
  # TODO(user): Add fields here
