// Code generated by counterfeiter. DO NOT EDIT.
package objectstoragefakes

import (
	"context"
	"sync"

	"github.com/go-logr/logr"

	"github.com/giantswarm/object-storage-operator/api/v1alpha1"
	"github.com/giantswarm/object-storage-operator/internal/pkg/cluster"
	"github.com/giantswarm/object-storage-operator/internal/pkg/service/objectstorage"
)

type FakeObjectStorageServiceFactory struct {
	NewAccessRoleServiceStub        func(context.Context, logr.Logger, cluster.Cluster) (objectstorage.AccessRoleService, error)
	newAccessRoleServiceMutex       sync.RWMutex
	newAccessRoleServiceArgsForCall []struct {
		arg1 context.Context
		arg2 logr.Logger
		arg3 cluster.Cluster
	}
	newAccessRoleServiceReturns struct {
		result1 objectstorage.AccessRoleService
		result2 error
	}
	newAccessRoleServiceReturnsOnCall map[int]struct {
		result1 objectstorage.AccessRoleService
		result2 error
	}
	NewObjectStorageServiceStub        func(context.Context, logr.Logger, cluster.Cluster, *v1alpha1.Bucket) (objectstorage.ObjectStorageService, error)
	newObjectStorageServiceMutex       sync.RWMutex
	newObjectStorageServiceArgsForCall []struct {
		arg1 context.Context
		arg2 logr.Logger
		arg3 cluster.Cluster
		arg4 *v1alpha1.Bucket
	}
	newObjectStorageServiceReturns struct {
		result1 objectstorage.ObjectStorageService
		result2 error
	}
	newObjectStorageServiceReturnsOnCall map[int]struct {
		result1 objectstorage.ObjectStorageService
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeObjectStorageServiceFactory) NewAccessRoleService(arg1 context.Context, arg2 logr.Logger, arg3 cluster.Cluster) (objectstorage.AccessRoleService, error) {
	fake.newAccessRoleServiceMutex.Lock()
	ret, specificReturn := fake.newAccessRoleServiceReturnsOnCall[len(fake.newAccessRoleServiceArgsForCall)]
	fake.newAccessRoleServiceArgsForCall = append(fake.newAccessRoleServiceArgsForCall, struct {
		arg1 context.Context
		arg2 logr.Logger
		arg3 cluster.Cluster
	}{arg1, arg2, arg3})
	stub := fake.NewAccessRoleServiceStub
	fakeReturns := fake.newAccessRoleServiceReturns
	fake.recordInvocation("NewAccessRoleService", []interface{}{arg1, arg2, arg3})
	fake.newAccessRoleServiceMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeObjectStorageServiceFactory) NewAccessRoleServiceCallCount() int {
	fake.newAccessRoleServiceMutex.RLock()
	defer fake.newAccessRoleServiceMutex.RUnlock()
	return len(fake.newAccessRoleServiceArgsForCall)
}

func (fake *FakeObjectStorageServiceFactory) NewAccessRoleServiceCalls(stub func(context.Context, logr.Logger, cluster.Cluster) (objectstorage.AccessRoleService, error)) {
	fake.newAccessRoleServiceMutex.Lock()
	defer fake.newAccessRoleServiceMutex.Unlock()
	fake.NewAccessRoleServiceStub = stub
}

func (fake *FakeObjectStorageServiceFactory) NewAccessRoleServiceArgsForCall(i int) (context.Context, logr.Logger, cluster.Cluster) {
	fake.newAccessRoleServiceMutex.RLock()
	defer fake.newAccessRoleServiceMutex.RUnlock()
	argsForCall := fake.newAccessRoleServiceArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeObjectStorageServiceFactory) NewAccessRoleServiceReturns(result1 objectstorage.AccessRoleService, result2 error) {
	fake.newAccessRoleServiceMutex.Lock()
	defer fake.newAccessRoleServiceMutex.Unlock()
	fake.NewAccessRoleServiceStub = nil
	fake.newAccessRoleServiceReturns = struct {
		result1 objectstorage.AccessRoleService
		result2 error
	}{result1, result2}
}

func (fake *FakeObjectStorageServiceFactory) NewAccessRoleServiceReturnsOnCall(i int, result1 objectstorage.AccessRoleService, result2 error) {
	fake.newAccessRoleServiceMutex.Lock()
	defer fake.newAccessRoleServiceMutex.Unlock()
	fake.NewAccessRoleServiceStub = nil
	if fake.newAccessRoleServiceReturnsOnCall == nil {
		fake.newAccessRoleServiceReturnsOnCall = make(map[int]struct {
			result1 objectstorage.AccessRoleService
			result2 error
		})
	}
	fake.newAccessRoleServiceReturnsOnCall[i] = struct {
		result1 objectstorage.AccessRoleService
		result2 error
	}{result1, result2}
}

func (fake *FakeObjectStorageServiceFactory) NewObjectStorageService(arg1 context.Context, arg2 logr.Logger, arg3 cluster.Cluster, arg4 *v1alpha1.Bucket) (objectstorage.ObjectStorageService, error) {
	fake.newObjectStorageServiceMutex.Lock()
	ret, specificReturn := fake.newObjectStorageServiceReturnsOnCall[len(fake.newObjectStorageServiceArgsForCall)]
	fake.newObjectStorageServiceArgsForCall = append(fake.newObjectStorageServiceArgsForCall, struct {
		arg1 context.Context
		arg2 logr.Logger
		arg3 cluster.Cluster
		arg4 *v1alpha1.Bucket
	}{arg1, arg2, arg3, arg4})
	stub := fake.NewObjectStorageServiceStub
	fakeReturns := fake.newObjectStorageServiceReturns
	fake.recordInvocation("NewObjectStorageService", []interface{}{arg1, arg2, arg3, arg4})
	fake.newObjectStorageServiceMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeObjectStorageServiceFactory) NewObjectStorageServiceCallCount() int {
	fake.newObjectStorageServiceMutex.RLock()
	defer fake.newObjectStorageServiceMutex.RUnlock()
	return len(fake.newObjectStorageServiceArgsForCall)
}

func (fake *FakeObjectStorageServiceFactory) NewObjectStorageServiceCalls(stub func(context.Context, logr.Logger, cluster.Cluster, *v1alpha1.Bucket) (objectstorage.ObjectStorageService, error)) {
	fake.newObjectStorageServiceMutex.Lock()
	defer fake.newObjectStorageServiceMutex.Unlock()
	fake.NewObjectStorageServiceStub = stub
}

func (fake *FakeObjectStorageServiceFactory) NewObjectStorageServiceArgsForCall(i int) (context.Context, logr.Logger, cluster.Cluster, *v1alpha1.Bucket) {
	fake.newObjectStorageServiceMutex.RLock()
	defer fake.newObjectStorageServiceMutex.RUnlock()
	argsForCall := fake.newObjectStorageServiceArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *FakeObjectStorageServiceFactory) NewObjectStorageServiceReturns(result1 objectstorage.ObjectStorageService, result2 error) {
	fake.newObjectStorageServiceMutex.Lock()
	defer fake.newObjectStorageServiceMutex.Unlock()
	fake.NewObjectStorageServiceStub = nil
	fake.newObjectStorageServiceReturns = struct {
		result1 objectstorage.ObjectStorageService
		result2 error
	}{result1, result2}
}

func (fake *FakeObjectStorageServiceFactory) NewObjectStorageServiceReturnsOnCall(i int, result1 objectstorage.ObjectStorageService, result2 error) {
	fake.newObjectStorageServiceMutex.Lock()
	defer fake.newObjectStorageServiceMutex.Unlock()
	fake.NewObjectStorageServiceStub = nil
	if fake.newObjectStorageServiceReturnsOnCall == nil {
		fake.newObjectStorageServiceReturnsOnCall = make(map[int]struct {
			result1 objectstorage.ObjectStorageService
			result2 error
		})
	}
	fake.newObjectStorageServiceReturnsOnCall[i] = struct {
		result1 objectstorage.ObjectStorageService
		result2 error
	}{result1, result2}
}

func (fake *FakeObjectStorageServiceFactory) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.newAccessRoleServiceMutex.RLock()
	defer fake.newAccessRoleServiceMutex.RUnlock()
	fake.newObjectStorageServiceMutex.RLock()
	defer fake.newObjectStorageServiceMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeObjectStorageServiceFactory) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ objectstorage.ObjectStorageServiceFactory = new(FakeObjectStorageServiceFactory)
