{{- if eq .Values.networkPolicy.flavor "cilium" -}}
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  labels:
    {{- include "labels.common" . | nindent 4 }}
  name: {{ include "resource.default.name"  . }}
  namespace: {{ include "resource.default.namespace"  . }}
spec:
  endpointSelector:
    matchLabels:
      {{- include "labels.selector" . | nindent 6 }}
  egress:
    - toEntities:
        - kube-apiserver
  ingress:
    - fromEntities:
        - cluster
{{- end -}}
