{{- if eq .Values.networkPolicy.flavor "kubernetes" -}}
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  labels:
    {{- include "labels.common" . | nindent 4 }}
  name: {{ include "resource.default.name"  . }}
  namespace: {{ include "resource.default.namespace"  . }}
spec:
  podSelector:
    matchLabels:
      {{- include "labels.selector" . | nindent 6 }}
  ingress:
  - ports:
    - port: 8000
      protocol: TCP
  egress:
  - {}
  policyTypes:
  - Egress
  - Ingress
{{- end -}}
