{{- if not .Values.global.podSecurityStandards.enforced }}
{{- if .Capabilities.APIVersions.Has "policy/v1beta1/PodSecurityPolicy" }}
{{- if eq .Values.managementCluster.provider.kind "capz" }}
apiVersion: kyverno.io/v2alpha1
kind: PolicyException
metadata:
  labels:
    {{- include "labels.common" . | nindent 4 }}
  name: {{ include "resource.policyException.name" . }}
  namespace: giantswarm
spec:
  exceptions:
  - policyName: disallow-host-ports
    ruleNames:
    - host-ports-none
    - autogen-host-ports-none
  - policyName: disallow-host-namespaces
    ruleNames:
    - host-namespaces
    - autogen-host-namespaces
  match:
    any:
    - resources:
        kinds:
        - Deployment
        - ReplicaSet
        - Pod
        names:
        - object-storage-operator*
        namespaces:
        - {{ include "resource.default.namespace" . }}
{{- end }}
{{- end }}
{{- end }}