{{- if not .Values.global.podSecurityStandards.enforced }}
{{- if .Capabilities.APIVersions.Has "policy/v1beta1/PodSecurityPolicy" }}
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  labels:
    {{- include "labels.common" . | nindent 4 }}
  name: {{ include "resource.psp.name" . }}
spec:
  privileged: false
  fsGroup:
    rule: MustRunAs
    ranges:
      - min: 1
        max: 65535
  runAsUser:
    rule: RunAsAny
  runAsGroup:
    rule: MustRunAs
    ranges:
      - min: 1
        max: 65535
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  allowPrivilegeEscalation: false
  {{ if eq .Values.managementCluster.provider.kind "capz" -}}
  hostNetwork: true
  {{- end }}
  hostIPC: false
  hostPID: false
{{- end }}
{{- end }}
