apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "labels.common" . | nindent 4 }}
  name: {{ include "resource.default.name" . }}
rules:
  # RBAC needed for all providers
  - apiGroups:
      - objectstorage.giantswarm.io
    resources:
      - buckets
      - buckets/status
    verbs:
      - watch
      - get
      - list
      - update
      - patch
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - get
      - create
      - update
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create

  {{ if eq .Values.managementCluster.provider.kind "capa" -}}
  - apiGroups:
      - infrastructure.cluster.x-k8s.io
    resources:
      - awsclusters
      - awsclusterroleidentities
    verbs:
      - get
      - list
      - watch
  {{- end}}

  {{ if eq .Values.managementCluster.provider.kind "capz" -}}
  - apiGroups:
      - infrastructure.cluster.x-k8s.io
    resources:
      - azureclusters
    verbs:
      - get
      - list
      - watch
  - apiGroups:
    - infrastructure.cluster.x-k8s.io
    resources:
    - azureclusteridentities
    - azureclusteridentities/status
    verbs:
    - get
    - list
    - patch
    - update
    - watch
  # Needed to store Azure storage account credentials
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - create
      - update
      - patch
      - delete
      - get
      - list
      - watch
  # Needed for Azure to detect private mode
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    {{- include "labels.common" . | nindent 4 }}
  name: {{ include "resource.default.name" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "resource.default.name" . }}
    namespace: {{ include "resource.default.namespace" . }}
roleRef:
  kind: ClusterRole
  name: {{ include "resource.default.name" . }}
  apiGroup: rbac.authorization.k8s.io
