apiVersion: v1
kind: ServiceAccount
metadata:
  {{- if and (eq .Values.managementCluster.provider.kind "capz") .Values.managementCluster.useAzureWorkloadIdentities }}
  annotations:
    azure.workload.identity/client-id: {{ required "managementCluster.azure.clientId is required when using Azure Workload Identities" .Values.managementCluster.azure.clientId | quote }}
    azure.workload.identity/use: "true"
  {{- end }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
  name: {{ include "resource.default.name" . }}
  namespace: {{ include "resource.default.namespace"  . }}
